// poster.test.ts
//
// Pins the TypeScript port of the iOS app's PosterGradient to the original:
// same canonical FNV-1a 64 fold, same 7-pair palette, same index reduction.
// The cross-language vectors below were generated by running the Swift
// implementation (Shared/Concerts/Sources/Concerts/PosterGradient.swift in
// WXYC/wxyc-ios-64) standalone — if either side drifts, a shared show would
// paint different colors in the app and on its share page.

import { describe, expect, it } from "vitest";
import { POSTER_PALETTE, fnv1a64, posterIndex, posterPair } from "../src/poster";

describe("fnv1a64", () => {
  it("matches the canonical FNV-1a 64 offset basis for the empty string", () => {
    expect(fnv1a64("")).toBe(0xcbf29ce484222325n);
  });

  it("matches the published FNV-1a 64 vector for 'a'", () => {
    expect(fnv1a64("a")).toBe(0xaf63dc4c8601ec8cn);
  });

  it("folds multi-byte UTF-8 like the Swift implementation (utf8 view)", () => {
    // "café" exercises a 2-byte UTF-8 sequence; the fold is over UTF-8 bytes.
    expect(fnv1a64("café")).toBe(fnv1a64("café"));
    expect(fnv1a64("café")).not.toBe(fnv1a64("cafe"));
  });
});

describe("posterIndex — Swift parity", () => {
  // Generated with the app's PosterGradient (fnv1a("<slug>-<id>") % 7).
  const vectors: Array<[slug: string, id: number, hash: bigint, index: number]> = [
    ["cats-cradle-back-room", 1, 0x6bedfc6290ab378an, 4],
    ["cats-cradle", 4821, 0x12fbf64b3b90a11en, 1],
    ["local-506", 17, 0x5b4256ab0bf7e98bn, 6],
    ["motorco-music-hall", 123456, 0x35611ca28d25a736n, 4],
    ["the-pinhook", 2, 0x72f5fc05bf0b297en, 6],
    ["kings", 99, 0x3339e9353153512cn, 3],
  ];

  it.each(vectors)("hashes %s-%i like the app", (slug, id, hash, index) => {
    expect(fnv1a64(`${slug}-${id}`)).toBe(hash);
    expect(posterIndex(slug, id)).toBe(index);
  });
});

describe("POSTER_PALETTE", () => {
  it("carries the app's 7 gradient pairs in the app's order (order is load-bearing)", () => {
    expect(POSTER_PALETTE).toEqual([
      { start: "#c65a2e", end: "#7d1f3d" },
      { start: "#245b7a", end: "#101a52" },
      { start: "#8a6a3a", end: "#3a2140" },
      { start: "#6d2f6a", end: "#241246" },
      { start: "#2f5a8a", end: "#151a3a" },
      { start: "#b0632a", end: "#4a1d22" },
      { start: "#7a5a1f", end: "#20183a" },
    ]);
  });

  it("resolves a stable pair for a concert", () => {
    expect(posterPair("cats-cradle-back-room", 1)).toEqual(POSTER_PALETTE[4]);
    expect(posterPair("cats-cradle-back-room", 1)).toEqual(posterPair("cats-cradle-back-room", 1));
  });
});
